[
  {
      "added_at": "2024-09-04T05:57:55Z",
      "added_by": {
          "external_urls": {
              "spotify": "https://open.spotify.com/user/21hvg3njanoivnfoddjxp2gra"
          },
          "href": "https://api.spotify.com/v1/users/21hvg3njanoivnfoddjxp2gra",
          "id": "21hvg3njanoivnfoddjxp2gra",
          "type": "user",
          "uri": "spotify:user:21hvg3njanoivnfoddjxp2gra"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
          "preview_url": "https://p.scdn.co/mp3-preview/5445cf0be8d5aefa199ddb77e056e60aa63f0e4f?cid=ee0874b4376c4fffb9273495646b6afb",
          "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "MK",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET"
          ],
          "explicit": false,
          "type": "track",
          "episode": false,
          "track": true,
          "album": {
              "available_markets": [
                  "AR",
                  "AU",
                  "AT",
                  "BE",
                  "BO",
                  "BR",
                  "BG",
                  "CA",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DK",
                  "DO",
                  "DE",
                  "EC",
                  "EE",
                  "SV",
                  "FI",
                  "FR",
                  "GR",
                  "GT",
                  "HN",
                  "HK",
                  "HU",
                  "IS",
                  "IE",
                  "IT",
                  "LV",
                  "LT",
                  "LU",
                  "MY",
                  "MT",
                  "MX",
                  "NL",
                  "NZ",
                  "NI",
                  "NO",
                  "PA",
                  "PY",
                  "PE",
                  "PH",
                  "PL",
                  "PT",
                  "SG",
                  "SK",
                  "ES",
                  "SE",
                  "CH",
                  "TW",
                  "TR",
                  "UY",
                  "US",
                  "GB",
                  "AD",
                  "LI",
                  "MC",
                  "ID",
                  "JP",
                  "TH",
                  "VN",
                  "RO",
                  "IL",
                  "ZA",
                  "SA",
                  "AE",
                  "BH",
                  "QA",
                  "OM",
                  "KW",
                  "EG",
                  "MA",
                  "DZ",
                  "TN",
                  "LB",
                  "JO",
                  "PS",
                  "IN",
                  "BY",
                  "KZ",
                  "MD",
                  "UA",
                  "AL",
                  "BA",
                  "HR",
                  "MK",
                  "SI",
                  "KR",
                  "BD",
                  "PK",
                  "LK",
                  "GH",
                  "KE",
                  "NG",
                  "TZ",
                  "UG",
                  "AG",
                  "AM",
                  "BS",
                  "BB",
                  "BZ",
                  "BT",
                  "BW",
                  "BF",
                  "CV",
                  "CW",
                  "DM",
                  "FJ",
                  "GM",
                  "GE",
                  "GD",
                  "GW",
                  "GY",
                  "HT",
                  "JM",
                  "KI",
                  "LS",
                  "LR",
                  "MW",
                  "MV",
                  "ML",
                  "MH",
                  "FM",
                  "NA",
                  "NR",
                  "NE",
                  "PW",
                  "PG",
                  "PR",
                  "WS",
                  "SM",
                  "ST",
                  "SN",
                  "SC",
                  "SL",
                  "SB",
                  "KN",
                  "LC",
                  "VC",
                  "SR",
                  "TL",
                  "TO",
                  "TT",
                  "TV",
                  "VU",
                  "AZ",
                  "BN",
                  "BI",
                  "KH",
                  "CM",
                  "TD",
                  "KM",
                  "GQ",
                  "SZ",
                  "GA",
                  "GN",
                  "KG",
                  "LA",
                  "MO",
                  "MR",
                  "MN",
                  "NP",
                  "RW",
                  "TG",
                  "UZ",
                  "ZW",
                  "BJ",
                  "MG",
                  "MU",
                  "MZ",
                  "AO",
                  "CI",
                  "DJ",
                  "ZM",
                  "CD",
                  "CG",
                  "IQ",
                  "LY",
                  "TJ",
                  "VE",
                  "ET"
              ],
              "type": "album",
              "album_type": "album",
              "href": "https://api.spotify.com/v1/albums/0R7O30pBkUHsY1M22gxpAh",
              "id": "0R7O30pBkUHsY1M22gxpAh",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/ab67616d0000b273039470eae22990827fc6fafd",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/ab67616d00001e02039470eae22990827fc6fafd",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/ab67616d00004851039470eae22990827fc6fafd",
                      "width": 64
                  }
              ],
              "name": "Zvido Zvenyu Kunyanya",
              "release_date": "2006-02-03",
              "release_date_precision": "day",
              "uri": "spotify:album:0R7O30pBkUHsY1M22gxpAh",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                      },
                      "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                      "id": "1s62AefEtb6RfV1bpDlL88",
                      "name": "Alick Macheso and Orchestra Mberikwazvo",
                      "type": "artist",
                      "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
                  }
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/0R7O30pBkUHsY1M22gxpAh"
              },
              "total_tracks": 8
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                  },
                  "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                  "id": "1s62AefEtb6RfV1bpDlL88",
                  "name": "Alick Macheso and Orchestra Mberikwazvo",
                  "type": "artist",
                  "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
              }
          ],
          "disc_number": 1,
          "track_number": 1,
          "duration_ms": 700666,
          "external_ids": {
              "isrc": "ZAG530900595"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3Lc4uMEy8tKukw32opZJzi"
          },
          "href": "https://api.spotify.com/v1/tracks/3Lc4uMEy8tKukw32opZJzi",
          "id": "3Lc4uMEy8tKukw32opZJzi",
          "name": "Madhawu",
          "popularity": 21,
          "uri": "spotify:track:3Lc4uMEy8tKukw32opZJzi",
          "is_local": false
      },
      "video_thumbnail": {
          "url": null
      }
  },
  {
      "added_at": "2024-09-04T05:58:08Z",
      "added_by": {
          "external_urls": {
              "spotify": "https://open.spotify.com/user/21hvg3njanoivnfoddjxp2gra"
          },
          "href": "https://api.spotify.com/v1/users/21hvg3njanoivnfoddjxp2gra",
          "id": "21hvg3njanoivnfoddjxp2gra",
          "type": "user",
          "uri": "spotify:user:21hvg3njanoivnfoddjxp2gra"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
          "preview_url": "https://p.scdn.co/mp3-preview/bd7969b3196148f97ad04d06512868ae33482506?cid=ee0874b4376c4fffb9273495646b6afb",
          "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "MK",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET"
          ],
          "explicit": false,
          "type": "track",
          "episode": false,
          "track": true,
          "album": {
              "available_markets": [
                  "AR",
                  "AU",
                  "AT",
                  "BE",
                  "BO",
                  "BR",
                  "BG",
                  "CA",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DK",
                  "DO",
                  "DE",
                  "EC",
                  "EE",
                  "SV",
                  "FI",
                  "FR",
                  "GR",
                  "GT",
                  "HN",
                  "HK",
                  "HU",
                  "IS",
                  "IE",
                  "IT",
                  "LV",
                  "LT",
                  "LU",
                  "MY",
                  "MT",
                  "MX",
                  "NL",
                  "NZ",
                  "NI",
                  "NO",
                  "PA",
                  "PY",
                  "PE",
                  "PH",
                  "PL",
                  "PT",
                  "SG",
                  "SK",
                  "ES",
                  "SE",
                  "CH",
                  "TW",
                  "TR",
                  "UY",
                  "US",
                  "GB",
                  "AD",
                  "LI",
                  "MC",
                  "ID",
                  "JP",
                  "TH",
                  "VN",
                  "RO",
                  "IL",
                  "ZA",
                  "SA",
                  "AE",
                  "BH",
                  "QA",
                  "OM",
                  "KW",
                  "EG",
                  "MA",
                  "DZ",
                  "TN",
                  "LB",
                  "JO",
                  "PS",
                  "IN",
                  "BY",
                  "KZ",
                  "MD",
                  "UA",
                  "AL",
                  "BA",
                  "HR",
                  "MK",
                  "SI",
                  "KR",
                  "BD",
                  "PK",
                  "LK",
                  "GH",
                  "KE",
                  "NG",
                  "TZ",
                  "UG",
                  "AG",
                  "AM",
                  "BS",
                  "BB",
                  "BZ",
                  "BT",
                  "BW",
                  "BF",
                  "CV",
                  "CW",
                  "DM",
                  "FJ",
                  "GM",
                  "GE",
                  "GD",
                  "GW",
                  "GY",
                  "HT",
                  "JM",
                  "KI",
                  "LS",
                  "LR",
                  "MW",
                  "MV",
                  "ML",
                  "MH",
                  "FM",
                  "NA",
                  "NR",
                  "NE",
                  "PW",
                  "PG",
                  "PR",
                  "WS",
                  "SM",
                  "ST",
                  "SN",
                  "SC",
                  "SL",
                  "SB",
                  "KN",
                  "LC",
                  "VC",
                  "SR",
                  "TL",
                  "TO",
                  "TT",
                  "TV",
                  "VU",
                  "AZ",
                  "BN",
                  "BI",
                  "KH",
                  "CM",
                  "TD",
                  "KM",
                  "GQ",
                  "SZ",
                  "GA",
                  "GN",
                  "KG",
                  "LA",
                  "MO",
                  "MR",
                  "MN",
                  "NP",
                  "RW",
                  "TG",
                  "UZ",
                  "ZW",
                  "BJ",
                  "MG",
                  "MU",
                  "MZ",
                  "AO",
                  "CI",
                  "DJ",
                  "ZM",
                  "CD",
                  "CG",
                  "IQ",
                  "LY",
                  "TJ",
                  "VE",
                  "ET"
              ],
              "type": "album",
              "album_type": "album",
              "href": "https://api.spotify.com/v1/albums/0R7O30pBkUHsY1M22gxpAh",
              "id": "0R7O30pBkUHsY1M22gxpAh",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/ab67616d0000b273039470eae22990827fc6fafd",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/ab67616d00001e02039470eae22990827fc6fafd",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/ab67616d00004851039470eae22990827fc6fafd",
                      "width": 64
                  }
              ],
              "name": "Zvido Zvenyu Kunyanya",
              "release_date": "2006-02-03",
              "release_date_precision": "day",
              "uri": "spotify:album:0R7O30pBkUHsY1M22gxpAh",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                      },
                      "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                      "id": "1s62AefEtb6RfV1bpDlL88",
                      "name": "Alick Macheso and Orchestra Mberikwazvo",
                      "type": "artist",
                      "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
                  }
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/0R7O30pBkUHsY1M22gxpAh"
              },
              "total_tracks": 8
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                  },
                  "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                  "id": "1s62AefEtb6RfV1bpDlL88",
                  "name": "Alick Macheso and Orchestra Mberikwazvo",
                  "type": "artist",
                  "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
              }
          ],
          "disc_number": 1,
          "track_number": 2,
          "duration_ms": 583466,
          "external_ids": {
              "isrc": "ZAG530900596"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/6svOg2cPisC8RBHZGOIGiz"
          },
          "href": "https://api.spotify.com/v1/tracks/6svOg2cPisC8RBHZGOIGiz",
          "id": "6svOg2cPisC8RBHZGOIGiz",
          "name": "Wemakonzo",
          "popularity": 30,
          "uri": "spotify:track:6svOg2cPisC8RBHZGOIGiz",
          "is_local": false
      },
      "video_thumbnail": {
          "url": null
      }
  },
  {
      "added_at": "2024-09-04T05:58:16Z",
      "added_by": {
          "external_urls": {
              "spotify": "https://open.spotify.com/user/21hvg3njanoivnfoddjxp2gra"
          },
          "href": "https://api.spotify.com/v1/users/21hvg3njanoivnfoddjxp2gra",
          "id": "21hvg3njanoivnfoddjxp2gra",
          "type": "user",
          "uri": "spotify:user:21hvg3njanoivnfoddjxp2gra"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
          "preview_url": "https://p.scdn.co/mp3-preview/99d13a64801ff4b899ede4e0dbecb4e77c5f9f11?cid=ee0874b4376c4fffb9273495646b6afb",
          "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "MK",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "PR",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET"
          ],
          "explicit": false,
          "type": "track",
          "episode": false,
          "track": true,
          "album": {
              "available_markets": [
                  "AR",
                  "AU",
                  "AT",
                  "BE",
                  "BO",
                  "BR",
                  "BG",
                  "CA",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DK",
                  "DO",
                  "DE",
                  "EC",
                  "EE",
                  "SV",
                  "FI",
                  "FR",
                  "GR",
                  "GT",
                  "HN",
                  "HK",
                  "HU",
                  "IS",
                  "IE",
                  "IT",
                  "LV",
                  "LT",
                  "LU",
                  "MY",
                  "MT",
                  "MX",
                  "NL",
                  "NZ",
                  "NI",
                  "NO",
                  "PA",
                  "PY",
                  "PE",
                  "PH",
                  "PL",
                  "PT",
                  "SG",
                  "SK",
                  "ES",
                  "SE",
                  "CH",
                  "TW",
                  "TR",
                  "UY",
                  "US",
                  "GB",
                  "AD",
                  "LI",
                  "MC",
                  "ID",
                  "JP",
                  "TH",
                  "VN",
                  "RO",
                  "IL",
                  "ZA",
                  "SA",
                  "AE",
                  "BH",
                  "QA",
                  "OM",
                  "KW",
                  "EG",
                  "MA",
                  "DZ",
                  "TN",
                  "LB",
                  "JO",
                  "PS",
                  "IN",
                  "BY",
                  "KZ",
                  "MD",
                  "UA",
                  "AL",
                  "BA",
                  "HR",
                  "MK",
                  "SI",
                  "KR",
                  "BD",
                  "PK",
                  "LK",
                  "GH",
                  "KE",
                  "NG",
                  "TZ",
                  "UG",
                  "AG",
                  "AM",
                  "BS",
                  "BB",
                  "BZ",
                  "BT",
                  "BW",
                  "BF",
                  "CV",
                  "CW",
                  "DM",
                  "FJ",
                  "GM",
                  "GE",
                  "GD",
                  "GW",
                  "GY",
                  "HT",
                  "JM",
                  "KI",
                  "LS",
                  "LR",
                  "MW",
                  "MV",
                  "ML",
                  "MH",
                  "FM",
                  "NA",
                  "NR",
                  "NE",
                  "PW",
                  "PG",
                  "PR",
                  "WS",
                  "SM",
                  "ST",
                  "SN",
                  "SC",
                  "SL",
                  "SB",
                  "KN",
                  "LC",
                  "VC",
                  "SR",
                  "TL",
                  "TO",
                  "TT",
                  "TV",
                  "VU",
                  "AZ",
                  "BN",
                  "BI",
                  "KH",
                  "CM",
                  "TD",
                  "KM",
                  "GQ",
                  "SZ",
                  "GA",
                  "GN",
                  "KG",
                  "LA",
                  "MO",
                  "MR",
                  "MN",
                  "NP",
                  "RW",
                  "TG",
                  "UZ",
                  "ZW",
                  "BJ",
                  "MG",
                  "MU",
                  "MZ",
                  "AO",
                  "CI",
                  "DJ",
                  "ZM",
                  "CD",
                  "CG",
                  "IQ",
                  "LY",
                  "TJ",
                  "VE",
                  "ET"
              ],
              "type": "album",
              "album_type": "album",
              "href": "https://api.spotify.com/v1/albums/0R7O30pBkUHsY1M22gxpAh",
              "id": "0R7O30pBkUHsY1M22gxpAh",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/ab67616d0000b273039470eae22990827fc6fafd",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/ab67616d00001e02039470eae22990827fc6fafd",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/ab67616d00004851039470eae22990827fc6fafd",
                      "width": 64
                  }
              ],
              "name": "Zvido Zvenyu Kunyanya",
              "release_date": "2006-02-03",
              "release_date_precision": "day",
              "uri": "spotify:album:0R7O30pBkUHsY1M22gxpAh",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                      },
                      "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                      "id": "1s62AefEtb6RfV1bpDlL88",
                      "name": "Alick Macheso and Orchestra Mberikwazvo",
                      "type": "artist",
                      "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
                  }
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/0R7O30pBkUHsY1M22gxpAh"
              },
              "total_tracks": 8
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                  },
                  "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                  "id": "1s62AefEtb6RfV1bpDlL88",
                  "name": "Alick Macheso and Orchestra Mberikwazvo",
                  "type": "artist",
                  "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
              }
          ],
          "disc_number": 1,
          "track_number": 6,
          "duration_ms": 604706,
          "external_ids": {
              "isrc": "ZAG530900600"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/1mRJxPjwu2paK5nCOycxz6"
          },
          "href": "https://api.spotify.com/v1/tracks/1mRJxPjwu2paK5nCOycxz6",
          "id": "1mRJxPjwu2paK5nCOycxz6",
          "name": "Charakupa",
          "popularity": 19,
          "uri": "spotify:track:1mRJxPjwu2paK5nCOycxz6",
          "is_local": false
      },
      "video_thumbnail": {
          "url": null
      }
  },
  {
      "added_at": "2024-09-04T05:58:53Z",
      "added_by": {
          "external_urls": {
              "spotify": "https://open.spotify.com/user/21hvg3njanoivnfoddjxp2gra"
          },
          "href": "https://api.spotify.com/v1/users/21hvg3njanoivnfoddjxp2gra",
          "id": "21hvg3njanoivnfoddjxp2gra",
          "type": "user",
          "uri": "spotify:user:21hvg3njanoivnfoddjxp2gra"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
          "preview_url": null,
          "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
          ],
          "explicit": false,
          "type": "track",
          "episode": false,
          "track": true,
          "album": {
              "available_markets": [
                  "AR",
                  "AU",
                  "AT",
                  "BE",
                  "BO",
                  "BR",
                  "BG",
                  "CA",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DK",
                  "DO",
                  "DE",
                  "EC",
                  "EE",
                  "SV",
                  "FI",
                  "FR",
                  "GR",
                  "GT",
                  "HN",
                  "HK",
                  "HU",
                  "IS",
                  "IE",
                  "IT",
                  "LV",
                  "LT",
                  "LU",
                  "MY",
                  "MT",
                  "MX",
                  "NL",
                  "NZ",
                  "NI",
                  "NO",
                  "PA",
                  "PY",
                  "PE",
                  "PH",
                  "PL",
                  "PT",
                  "SG",
                  "SK",
                  "ES",
                  "SE",
                  "CH",
                  "TW",
                  "TR",
                  "UY",
                  "US",
                  "GB",
                  "AD",
                  "LI",
                  "MC",
                  "ID",
                  "JP",
                  "TH",
                  "VN",
                  "RO",
                  "IL",
                  "ZA",
                  "SA",
                  "AE",
                  "BH",
                  "QA",
                  "OM",
                  "KW",
                  "EG",
                  "MA",
                  "DZ",
                  "TN",
                  "LB",
                  "JO",
                  "PS",
                  "IN",
                  "BY",
                  "KZ",
                  "MD",
                  "UA",
                  "AL",
                  "BA",
                  "HR",
                  "ME",
                  "MK",
                  "RS",
                  "SI",
                  "KR",
                  "BD",
                  "PK",
                  "LK",
                  "GH",
                  "KE",
                  "NG",
                  "TZ",
                  "UG",
                  "AG",
                  "AM",
                  "BS",
                  "BB",
                  "BZ",
                  "BT",
                  "BW",
                  "BF",
                  "CV",
                  "CW",
                  "DM",
                  "FJ",
                  "GM",
                  "GE",
                  "GD",
                  "GW",
                  "GY",
                  "HT",
                  "JM",
                  "KI",
                  "LS",
                  "LR",
                  "MW",
                  "MV",
                  "ML",
                  "MH",
                  "FM",
                  "NA",
                  "NR",
                  "NE",
                  "PW",
                  "PG",
                  "WS",
                  "SM",
                  "ST",
                  "SN",
                  "SC",
                  "SL",
                  "SB",
                  "KN",
                  "LC",
                  "VC",
                  "SR",
                  "TL",
                  "TO",
                  "TT",
                  "TV",
                  "VU",
                  "AZ",
                  "BN",
                  "BI",
                  "KH",
                  "CM",
                  "TD",
                  "KM",
                  "GQ",
                  "SZ",
                  "GA",
                  "GN",
                  "KG",
                  "LA",
                  "MO",
                  "MR",
                  "MN",
                  "NP",
                  "RW",
                  "TG",
                  "UZ",
                  "ZW",
                  "BJ",
                  "MG",
                  "MU",
                  "MZ",
                  "AO",
                  "CI",
                  "DJ",
                  "ZM",
                  "CD",
                  "CG",
                  "IQ",
                  "LY",
                  "TJ",
                  "VE",
                  "ET",
                  "XK"
              ],
              "type": "album",
              "album_type": "album",
              "href": "https://api.spotify.com/v1/albums/25evDKAhOMM1C0PCFgAvHA",
              "id": "25evDKAhOMM1C0PCFgAvHA",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/ab67616d0000b273b93e5db9bc46cdae1ff2a828",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/ab67616d00001e02b93e5db9bc46cdae1ff2a828",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/ab67616d00004851b93e5db9bc46cdae1ff2a828",
                      "width": 64
                  }
              ],
              "name": "Vapupuri Pupurai",
              "release_date": "2005-01-01",
              "release_date_precision": "day",
              "uri": "spotify:album:25evDKAhOMM1C0PCFgAvHA",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                      },
                      "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                      "id": "1s62AefEtb6RfV1bpDlL88",
                      "name": "Alick Macheso and Orchestra Mberikwazvo",
                      "type": "artist",
                      "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
                  }
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/25evDKAhOMM1C0PCFgAvHA"
              },
              "total_tracks": 7
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/1s62AefEtb6RfV1bpDlL88"
                  },
                  "href": "https://api.spotify.com/v1/artists/1s62AefEtb6RfV1bpDlL88",
                  "id": "1s62AefEtb6RfV1bpDlL88",
                  "name": "Alick Macheso and Orchestra Mberikwazvo",
                  "type": "artist",
                  "uri": "spotify:artist:1s62AefEtb6RfV1bpDlL88"
              }
          ],
          "disc_number": 1,
          "track_number": 1,
          "duration_ms": 533130,
          "external_ids": {
              "isrc": "GB96Z1101473"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3JFltZhXtoKNkVHkXPPgvG"
          },
          "href": "https://api.spotify.com/v1/tracks/3JFltZhXtoKNkVHkXPPgvG",
          "id": "3JFltZhXtoKNkVHkXPPgvG",
          "name": "Makandidana",
          "popularity": 29,
          "uri": "spotify:track:3JFltZhXtoKNkVHkXPPgvG",
          "is_local": false
      },
      "video_thumbnail": {
          "url": null
      }
  }
]